function(g2l_thing_init)
    message(STATUS "-------------- G2Labs --------------")
    message(STATUS "G2Labs Thing firmware build system")
    message(STATUS "Target platform: ${G2L_PLATFORM}")
    message(STATUS "Target platform flavor: ${G2L_PLATFORM_FLAVOR}")
    message(STATUS "-------------- G2Labs --------------")
    include(${CMAKE_CURRENT_LIST_DIR}/cmake/platforms/init.${G2L_PLATFORM}${G2L_PLATFORM_FLAVOR}.cmake)
endfunction()

function(g2l_thing_build_executable executable)
    g2l_thing_platform_build_executable(${executable})
endfunction(g2l_thing_build_executable)

function(g2l_thing_add_source_platform_dependent_directory directory_root)
    set(source_platform_directory ${directory_root}/${G2L_PLATFORM}${G2L_PLATFORM_FLAVOR})

    if(EXISTS ${source_platform_directory})
        add_subdirectory(${source_platform_directory})
    else()
        message(FATAL_ERROR "Directory ${source_platform_directory} does not exist")
    endif()
endfunction()
